---
title: "Readme"
author: "Antti Raatevaara"
date: November 4, 2018
output: github_document
urlcolor: blue
---

## Introduction to Open Data Science

This is the **official** README-file of my IODS-project.
Rmd-files (Chapter 1-6) contain the exercises completed in this course.
Files are updated on weekly basis while course progresses.

***

Topics of the project:

* Regression and model validation (CH2)

* Logistic regression (CH3)

* Clustering and classification (CH4)

* Dimensionality reduction techniques (CH5)

* Analysis of longitudinal data (CH6)

Results can be examined from my course diary page, at [[Diary]](https://raatevaa.github.io/IODS-project/)





<br>
<br>
<br>
<br>

> Session info

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252   
[3] LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                    
[5] LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1    
 [6] yaml_2.2.0      Rcpp_0.12.19    rmarkdown_1.10  knitr_1.20      digest_0.6.18  
[11] evaluate_0.12  

> Note

Had several issues with Rmarkdown-installation:

Knitting HTML did not work: *"Rendering R Markdown documents requires an updated version of the rmarkdown package"* 

  + Solved issue by updating R-version from 3.0 to 3.4










  